version: "3.9"
services:
  client:
    container_name: 'docker-todo-client'
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    expose:
      - '3000'
    restart: always
    depends_on:
      - server
  server:
    container_name: 'docker-todo-server'
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - '4200:4200'
    expose:
      - '4200'
    restart: always
    depends_on:
      - redis
      - mysql
  redis:
    container_name: 'docker-count-redis'
    image: "redis"
    expose:
      - '6379'
    ports:
      - '6379:6379'
  mysql:
    container_name: 'docker-todo-mysql'
    image: 'mysql'
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=docker_todo_list
    expose:
      - '3306'
    ports:
      - '3306:3306'
